Import Libraries

In [16]:
import pandas as pd
import numpy as np
import neattext.functions as ntx

In [ ]:
#Load DataViz Package
import seaborn as sb

In [ ]:
#Load ML Pkgs
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB

Read dataset

In [ ]:
data_set_path = 'C:\\Users\\mlsob\\OneDrive\\Documentos\\Pagaleve\\dataset\\'

corpus = pd.read_csv(data_set_path+'Base_Safra_mar-abr22.csv', header=(0), sep=";")

In [11]:
corpus.head()

,customerid,planid,Anomes_ref,dataref,orderAmount,Saldo_Financiado,flag_d23,over5_D23,atraso_D23,score,idade,renda,Flag_Existente,flag_restritivo,flag_protesto,numberOfInstallments,items
0,462185ad-79d8-4ec3-bafc-ec2818f5b45d,0f5aaef2-aefb-483b-b8c1-58a8d4691b88,202204,26/04/2022,71.1,53.32,1,0.0,0,273,28,"2,712.92",1,0,0,4,"CAMISETA FUSCA PRETO - P, Embalagem pra Presente"
1,082d660a-4033-4a93-86f1-b9484770448a,52dbce69-2bcd-4a5c-9875-9c863fac721e,202204,26/04/2022,304,78,1,0.0,0,600,29,"1,801.27",0,0,0,4,calça jeans reta bicolor boywish mundo lolita ...
2,04813a97-e1ba-4ecc-8f73-fcf3b3dde8a2,d4a4fdf1-b19e-4fb7-aeeb-c4a611454ee1,202204,26/04/2022,117,87.75,1,0.0,0,881,35,"3,324.04",0,0,0,4,Kit de Body para Bebê Pica-pau Bordado - 2 peç...
3,0e84b174-5721-492c-82e7-f38979bc75e9,b6130bb4-3859-4d02-87a5-8f85209bcc40,202204,26/04/2022,142.2,106.65,1,0.0,0,694,31,"3,003.34",0,0,0,4,"CAMISETA PICA-PAU MEME BRANCO - M, Embalagem p..."
4,40c0ce62-8bee-4ce6-8746-61e6c1ee0943,fdc12cd5-c6dc-4f95-a129-773bd534b3ba,202204,26/04/2022,277.39,170.54,1,0.0,0,676,35,"3,541.2",0,0,0,4,vestido ombro único saturno mundo lolita M - 3...

In [19]:
df = corpus[["items", "over5_D23"]]
df.head()

                                               items  over5_D23
0   CAMISETA FUSCA PRETO - P, Embalagem pra Presente        0.0
1  calça jeans reta bicolor boywish mundo lolita ...        0.0
2  Kit de Body para Bebê Pica-pau Bordado - 2 peç...        0.0
3  CAMISETA PICA-PAU MEME BRANCO - M, Embalagem p...        0.0
4  vestido ombro único saturno mundo lolita M - 3...        0.0

### Text Processing
+ Reduce Noise
    - Punct
    - Special Characteres
    - Stop Words
+ Lemmantization/Stemming

In [17]:
dir(ntx)

['BTC_ADDRESS_REGEX',
 'CURRENCY_REGEX',
 'CURRENCY_SYMB_REGEX',
 'Counter',
 'DATE_REGEX',
 'EMAIL_REGEX',
 'EMOJI_REGEX',
 'HASTAG_REGEX',
 'MASTERCard_REGEX',
 'MD5_SHA_REGEX',
 'MOST_COMMON_PUNCT_REGEX',
 'NUMBERS_REGEX',
 'PHONE_REGEX',
 'PoBOX_REGEX',
 'SPECIAL_CHARACTERS_REGEX',
 'STOPWORDS',
 'STOPWORDS_de',
 'STOPWORDS_en',
 'STOPWORDS_es',
 'STOPWORDS_fr',
 'STOPWORDS_ru',
 'STOPWORDS_yo',
 'STREET_ADDRESS_REGEX',
 'TextFrame',
 'URL_PATTERN',
 'USER_HANDLES_REGEX',
 'VISACard_REGEX',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__generate_text',
 '__loader__',
 '__name__',
 '__numbers_dict',
 '__package__',
 '__spec__',
 '_lex_richness_herdan',
 '_lex_richness_maas_ttr',
 'clean_text',
 'defaultdict',
 'digit2words',
 'extract_btc_address',
 'extract_currencies',
 'extract_currency_symbols',
 'extract_dates',
 'extract_emails',
 'extract_emojis',
 'extract_hashtags',
 'extract_html_tags',
 'extract_mastercard_addr',
 'extract_md5sha',
 'extract_numbers',
 'extract_pattern',
 'extract_phone_numbers',
 'extract_postoffice_box',
 'extract_shortwords',
 'extract_special_characters',
 'extract_stopwords',
 'extract_street_address',
 'extract_terms_in_bracket',
 'extract_urls',
 'extract_userhandles',
 'extract_visacard_addr',
 'fix_contractions',
 'generate_sentence',
 'hamming_distance',
 'inverse_df',
 'lexical_richness',
 'markov_chain',
 'math',
 'nlargest',
 'normalize',
 'num2words',
 'random',
 're',
 'read_txt',
 'remove_accents',
 'remove_bad_quotes',
 'remove_btc_address',
 'remove_currencies',
 'remove_currency_symbols',
 'remove_custom_pattern',
 'remove_custom_words',
 'remove_dates',
 'remove_emails',
 'remove_emojis',
 'remove_hashtags',
 'remove_html_tags',
 'remove_mastercard_addr',
 'remove_md5sha',
 'remove_multiple_spaces',
 'remove_non_ascii',
 'remove_numbers',
 'remove_phone_numbers',
 'remove_postoffice_box',
 'remove_puncts',
 'remove_punctuations',
 'remove_shortwords',
 'remove_special_characters',
 'remove_stopwords',
 'remove_street_address',
 'remove_terms_in_bracket',
 'remove_urls',
 'remove_userhandles',
 'remove_visacard_addr',
 'replace_bad_quotes',
 'replace_currencies',
 'replace_currency_symbols',
 'replace_dates',
 'replace_emails',
 'replace_emojis',
 'replace_numbers',
 'replace_phone_numbers',
 'replace_special_characters',
 'replace_term',
 'replace_urls',
 'string',
 'term_freq',
 'to_txt',
 'unicodedata',
 'word_freq',
 'word_length_freq']

In [26]:
# Remove stopwords
df["clean_items"] = df["items"].apply(ntx.remove_stopwords)
df [["clean_items", "items"]]

C:\Users\mlsob\AppData\Local\Temp\ipykernel_54416\3457987569.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["clean_items"] = df["items"].apply(ntx.remove_stopwords)

,clean_items,items
0,"CAMISETA FUSCA PRETO - P, Embalagem pra Presente","CAMISETA FUSCA PRETO - P, Embalagem pra Presente"
1,calça jeans reta bicolor boywish mundo lolita ...,calça jeans reta bicolor boywish mundo lolita ...
2,Kit de Body para Bebê Pica-pau Bordado - 2 peç...,Kit de Body para Bebê Pica-pau Bordado - 2 peç...
3,"CAMISETA PICA-PAU MEME BRANCO - M, Embalagem p...","CAMISETA PICA-PAU MEME BRANCO - M, Embalagem p..."
4,vestido ombro único saturno mundo lolita - 38129,vestido ombro único saturno mundo lolita M - 3...
...,...,...
3771,Óculos de sol mormaii aruba 2 detalhe preto,Óculos de sol mormaii aruba 2 detalhe preto
3772,"TENIS RMI #079 BB ROYAL - 19/20, Embalagem pra...","TENIS RMI #079 BB ROYAL - 19/20, Embalagem pra..."
3773,KIT 2 POLOS PIQUET FLAME BRANCO/PRETO -,KIT 2 POLOS PIQUET FLAME BRANCO/PRETO - M
3774,CALÇA RESERVA MINI 5 POCKETS MOLETOM BORDEAUX ...,CALÇA RESERVA MINI 5 POCKETS MOLETOM BORDEAUX ...
3775,"TÊNIS ASHER RESERVA CARAMELO - 39, BERMUDA CAS...","TÊNIS ASHER RESERVA CARAMELO - 39, BERMUDA CAS..."

In [24]:
# Remove special characters
df["clean_items"] = df["clean_items"].apply(ntx.remove_special_characters)
df [["clean_items", "items"]]

C:\Users\mlsob\AppData\Local\Temp\ipykernel_54416\3796194275.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["clean_items"] = df["clean_items"].apply(ntx.remove_special_characters)

,clean_items,items
0,CAMISETA FUSCA PRETO P Embalagem pra Presente,"CAMISETA FUSCA PRETO - P, Embalagem pra Presente"
1,cala jeans reta bicolor boywish mundo lolita 3...,calça jeans reta bicolor boywish mundo lolita ...
2,Kit de Body para Beb Picapau Bordado 2 peas B...,Kit de Body para Bebê Pica-pau Bordado - 2 peç...
3,CAMISETA PICAPAU MEME BRANCO M Embalagem pra ...,"CAMISETA PICA-PAU MEME BRANCO - M, Embalagem p..."
4,vestido ombro nico saturno mundo lolita 38129,vestido ombro único saturno mundo lolita M - 3...
...,...,...
3771,culos de sol mormaii aruba 2 detalhe preto,Óculos de sol mormaii aruba 2 detalhe preto
3772,TENIS RMI 079 BB ROYAL 1920 Embalagem pra Pre...,"TENIS RMI #079 BB ROYAL - 19/20, Embalagem pra..."
3773,KIT 2 POLOS PIQUET FLAME BRANCOPRETO,KIT 2 POLOS PIQUET FLAME BRANCO/PRETO - M
3774,CALA RESERVA MINI 5 POCKETS MOLETOM BORDEAUX ...,CALÇA RESERVA MINI 5 POCKETS MOLETOM BORDEAUX ...
3775,TNIS ASHER RESERVA CARAMELO 39 BERMUDA CASUAL...,"TÊNIS ASHER RESERVA CARAMELO - 39, BERMUDA CAS..."

In [25]:
# Reduce to lowercase
df["clean_items"] = df["clean_items"].str.lower()
df [["clean_items", "items"]]

C:\Users\mlsob\AppData\Local\Temp\ipykernel_54416\1972429336.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["clean_items"] = df["clean_items"].str.lower()

,clean_items,items
0,camiseta fusca preto p embalagem pra presente,"CAMISETA FUSCA PRETO - P, Embalagem pra Presente"
1,cala jeans reta bicolor boywish mundo lolita 3...,calça jeans reta bicolor boywish mundo lolita ...
2,kit de body para beb picapau bordado 2 peas b...,Kit de Body para Bebê Pica-pau Bordado - 2 peç...
3,camiseta picapau meme branco m embalagem pra ...,"CAMISETA PICA-PAU MEME BRANCO - M, Embalagem p..."
4,vestido ombro nico saturno mundo lolita 38129,vestido ombro único saturno mundo lolita M - 3...
...,...,...
3771,culos de sol mormaii aruba 2 detalhe preto,Óculos de sol mormaii aruba 2 detalhe preto
3772,tenis rmi 079 bb royal 1920 embalagem pra pre...,"TENIS RMI #079 BB ROYAL - 19/20, Embalagem pra..."
3773,kit 2 polos piquet flame brancopreto,KIT 2 POLOS PIQUET FLAME BRANCO/PRETO - M
3774,cala reserva mini 5 pockets moletom bordeaux ...,CALÇA RESERVA MINI 5 POCKETS MOLETOM BORDEAUX ...
3775,tnis asher reserva caramelo 39 bermuda casual...,"TÊNIS ASHER RESERVA CARAMELO - 39, BERMUDA CAS..."

### Buiding Features From The Text
+ Convert words to vector of number
+ Tfidf matrix
+ Count
+ Hash vector

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [28]:
Xfeatures = df["clean_items"]
yLabels = df["over5_D23"]

In [29]:
Xfeatures.head()

0     CAMISETA FUSCA PRETO - P, Embalagem pra Presente
1    calça jeans reta bicolor boywish mundo lolita ...
2    Kit de Body para Bebê Pica-pau Bordado - 2 peç...
3    CAMISETA PICA-PAU MEME BRANCO - M, Embalagem p...
4     vestido ombro único saturno mundo lolita - 38129
Name: clean_items, dtype: object

In [31]:
tfidf_vec = TfidfVectorizer()
X = tfidf_vec.fit_transform(Xfeatures)

In [32]:
X

<3776x3993 sparse matrix of type '<class 'numpy.float64'>'
	with 39922 stored elements in Compressed Sparse Row format>

In [34]:
X.todense()

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [35]:
# Convert to DataFrame
df_vec = pd.DataFrame(X.todense(), columns=tfidf_vec.get_feature_names())

c:\Users\mlsob\Developer\Notebooks\credit-risk-predict\venv\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

In [36]:
df_vec

,00,00002,00003,00079,0036,0037,004638,007,00879,01,...,étnico,índigo,íons,íris,óculos,óleo,óptico,ômega,única,único
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.355922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3771,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.423892,0.0,0.0,0.0,0.0,0.000000
3772,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
3773,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
3774,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
3775,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000

In [37]:
# Transverse
df_vec.T

,0,1,2,3,4,5,6,7,8,9,...,3766,3767,3768,3769,3770,3771,3772,3773,3774,3775
00,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
00002,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
00003,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
00079,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
0036,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
óleo,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
óptico,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ômega,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
única,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
único,0.0,0.0,0.0,0.0,0.355922,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0